const API_CONST = {

 	N_INDOOR_FEATURE_LIST 			: 			'N_INDOOR_FEATURE_LIST',	
 	N_OUTDOOR_FEATURE_LIST 			: 			'N_OUTDOOR_FEATURE_LIST',	
 	N_SAVE_SEARCH_PROPERTY 			: 			'N_SAVE_SEARCH_PROPERTY',

 	N_GET_SAVED_SEARCH_PROPERTY 	: 			'N_GET_SAVED_SEARCH_PROPERTY',	
 	
 	N_PROPERTY_INFO_BYSEARCH 		: 			'N_PROPERTY_INFO_BYSEARCH',
 	N_SAVE_FAV_PROPERTY 			: 			'N_SAVE_FAV_PROPERTY',

 	N_GET_PROPERTY_DETAILS 			: 			'N_GET_PROPERTY_DETAILS',
 	N_SAVE_FAV_PROPERTY_DETAIL 		: 			'N_SAVE_FAV_PROPERTY_DETAIL',

 	N_REGISTER_USER 				: 			'N_REGISTER_USER',
 	N_GET_TOKEN 					: 			'N_GET_TOKEN',
 	N_GET_EXT_TOKEN 				: 			'N_GET_EXT_TOKEN',
 	N_LOGGED_IN_USER_DETAIL 		: 			'N_LOGGED_IN_USER_DETAIL',

 	N_GET_RENTAL_RESUME_STATES 		: 			'N_GET_RENTAL_RESUME_STATES',

 	N_GET_STATE_LIST 				: 			'N_GET_STATE_LIST',
 	N_GET_COUNTRY_LIST 				: 			'N_GET_COUNTRY_LIST',

 	N_GET_TENANT_DETAILS 			: 			'N_GET_TENANT_DETAILS',
 	N_UPDATE_TENANT_DETAILS 		: 			'N_UPDATE_TENANT_DETAILS',
 	N_DELETE_CO_APPLICANT_INFO 		: 			'N_DELETE_CO_APPLICANT_INFO',

 	N_GET_TENANT_RESIDENT_INFO 		: 			'N_GET_TENANT_RESIDENT_INFO',
 	N_UPDATE_TENANT_RESIDENT_INFO 	: 			'N_UPDATE_TENANT_RESIDENT_INFO',

 	N_GET_TENANT_PETS_INFO 			: 			'N_GET_TENANT_PETS_INFO',
 	N_UPDATE_TENANT_PETS_INFO 		: 			'N_UPDATE_TENANT_PETS_INFO',
 	N_DELETE_TENANT_PETS_INFO 		: 			'N_DELETE_TENANT_PETS_INFO',

 	N_GET_TENANT_CURRENT_RES_INFO 	: 			'N_GET_TENANT_CURRENT_RES_INFO',
 	N_UPDATE_TENANT_CURRENT_RES_INFO: 			'N_UPDATE_TENANT_CURRENT_RES_INFO',

 	N_GET_TENANT_PRE_RES_INFO 		: 			'N_GET_TENANT_PRE_RES_INFO',
 	N_UPDATE_TENANT_PRE_RES_INFO	: 			'N_UPDATE_TENANT_PRE_RES_INFO',
 	
 	N_GET_TENANT_CURRENT_EMP		: 			'N_GET_TENANT_CURRENT_EMP',
 	N_UPDATE_TENANT_CURRENT_EMP		: 			'N_UPDATE_TENANT_CURRENT_EMP',

 	N_GET_TENANT_PERSONAL_REF 		: 			'N_GET_TENANT_PERSONAL_REF',
	N_UPDATE_TENANT_PERSONAL_REF 	: 			'N_UPDATE_TENANT_PERSONAL_REF',

	N_GET_TENANT_PREVIOUS_EMP 		: 			'N_GET_TENANT_PREVIOUS_EMP',
	N_UPDATE_TENANT_PREVIOUS_EMP 	: 			'N_UPDATE_TENANT_PREVIOUS_EMP',

	N_GET_TENANT_IDENT_DOCUMENT 	: 			'N_GET_TENANT_IDENT_DOCUMENT',
	N_DELETE_TENANT_IDENT_DOCUMENT 	: 			'N_DELETE_TENANT_IDENT_DOCUMENT',

	N_GET_WEATHER_UPDATES 			: 			'N_GET_WEATHER_UPDATES',

	N_UPLOAD_TENANT_IDENTITY_DOC   	: 			'N_UPLOAD_TENANT_IDENTITY_DOC',

	N_GET_TENANT_BID_DETAILS 		: 			'N_GET_TENANT_BID_DETAILS',
	
}
export default API_CONST