const ACTION_TYPES = {

	SIGNIN_USERNAME_CHANGED									: 	'SIGNIN_USERNAME_CHANGED',
	SIGNIN_PASSWORD_CHANGED 								: 	'SIGNIN_PASSWORD_CHANGED',

	GET_TOKEN_RES 											: 	'GET_TOKEN_RES',
	CLEAR_GET_TOKEN_RESPONSE 								: 	'CLEAR_GET_TOKEN_RESPONSE',

	GET_EXT_TOKEN_RES 										: 	'GET_EXT_TOKEN_RES',
	CLEAR_GET_EXT_TOKEN_RESPONSE 							: 	'CLEAR_GET_EXT_TOKEN_RESPONSE',
	
	SIGNUP_FIRSTNAME_CHANGED 								: 	'SIGNUP_FIRSTNAME_CHANGED',
	SIGNUP_LASTNAME_CHANGED 								: 	'SIGNUP_LASTNAME_CHANGED',
	SIGNUP_EMAIL_CHANGED 									: 	'SIGNUP_EMAIL_CHANGED',
	SIGNUP_PASSWORD_CHANGED 								: 	'SIGNUP_PASSWORD_CHANGED',
	SIGNUP_CONFIRM_PASSWORD_CHANGED 						: 	'SIGNUP_CONFIRM_PASSWORD_CHANGED',
	
	REGISTER_USER_RES 										: 	'REGISTER_USER_RES',
	CLEAR_REGISTER_USER_RESPONSE 							: 	'CLEAR_REGISTER_USER_RESPONSE',	

	LOGGED_IN_USER_DETAIL_RESP 								: 	'LOGGED_IN_USER_DETAIL_RESP',
	CLEAR_LOGGED_IN_USER_DETAIL_RESPONSE					: 	'CLEAR_LOGGED_IN_USER_DETAIL_RESPONSE',

	GET_INDOOR_FEATURE_LIST_ACTION 							: 	'GET_INDOOR_FEATURE_LIST_ACTION',
	GET_OUTDOOR_FEATURE_LIST_ACTION 						: 	'GET_OUTDOOR_FEATURE_LIST_ACTION',

	CLEAR_GET_INDOOR_FEATURE_LIST_ACTION 					: 	'CLEAR_GET_INDOOR_FEATURE_LIST_ACTION',
	CLEAR_GET_OUTDOOR_FEATURE_LIST_ACTION 					: 	'CLEAR_GET_OUTDOOR_FEATURE_LIST_ACTION',

	USER_AUTHENTICATED										: 	'USER_AUTHENTICATED',

	PROPERTY_INFO_BYSEARCH 									: 	'PROPERTY_INFO_BYSEARCH',
	CLEAR_PROPERTY_INFO_BYSEARCH_ACTION 					: 	'CLEAR_PROPERTY_INFO_BYSEARCH_ACTION',	

	GET_PROPERTY_DETAILS_ACTION 							: 	'GET_PROPERTY_DETAILS_ACTION',
	CLEAR_GET_PROPERTY_DETAILS_ACTION	 					: 	'CLEAR_GET_PROPERTY_DETAILS_ACTION',

	SAVE_SEARCH_PROPERTY_ACTION 							: 	'SAVE_SEARCH_PROPERTY_ACTION',
	GET_SAVED_SEARCH_PROPERTY_ACTION 						:  	'GET_SAVED_SEARCH_PROPERTY_ACTION',
	CLEAR_GET_SAVED_SEARCH_PROPERTY_ACTION 					: 	'CLEAR_GET_SAVED_SEARCH_PROPERTY_ACTION',

	SAVE_FAV_PROPERTY_ACTION 								: 	'SAVE_FAV_PROPERTY_ACTION',
	CLEAR_SAVE_FAV_PROPERTY_ACTION 							: 	'CLEAR_SAVE_FAV_PROPERTY_ACTION',

	SAVE_FAV_PROPERTY_DETAIL_ACTION 						: 	'SAVE_FAV_PROPERTY_DETAIL_ACTION',
	CLEAR_SAVE_FAV_PROPERTY_DETAIL_ACTION 					: 	'CLEAR_SAVE_FAV_PROPERTY_DETAIL_ACTION',

	GET_RENTAL_RESUME_STATES_ACTION 						: 	'GET_RENTAL_RESUME_STATES_ACTION',
	CLEAR_GET_RENTAL_RESUME_STATES_ACTION 					: 	'CLEAR_GET_RENTAL_RESUME_STATES_ACTION',

	REFRESH_RENTAL_RESUME_MENU 								: 	'REFRESH_RENTAL_RESUME_MENU',
	STOP_REFRESH_RENTAL_RESUME_MENU 						: 	'STOP_REFRESH_RENTAL_RESUME_MENU',
	
	GET_STATE_LIST_ACTION 									: 	'GET_STATE_LIST_ACTION',
	GET_COUNTRY_LIST_ACTION 								: 	'GET_COUNTRY_LIST_ACTION',
	CLEAR_GET_STATE_LIST_ACTION 							: 	'CLEAR_GET_STATE_LIST_ACTION',
	CLEAR_GET_COUNTRY_LIST_ACTION 							: 	'CLEAR_GET_COUNTRY_LIST_ACTION',

	GET_TENANT_DETAILS_ACTION 								: 	'GET_TENANT_DETAILS_ACTION',
	GET_TENANT_RESIDENT_INFO_ACTION 						: 	'GET_TENANT_RESIDENT_INFO_ACTION',
	GET_TENANT_PETS_INFO_ACTION 							: 	'GET_TENANT_PETS_INFO_ACTION',
	GET_TENANT_CURRENT_RES_INFO_ACTION 						: 	'GET_TENANT_CURRENT_RES_INFO_ACTION',
	GET_TENANT_PRE_RES_INFO_ACTION 							: 	'GET_TENANT_PRE_RES_INFO_ACTION',
	GET_TENANT_PERSONAL_REF_ACTION 							: 	'GET_TENANT_PERSONAL_REF_ACTION',
	GET_TENANT_CURRENT_EMP_ACTION 							: 	'GET_TENANT_CURRENT_EMP_ACTION',
	GET_TENANT_PREVIOUS_EMP_ACTION 							: 	'GET_TENANT_PREVIOUS_EMP_ACTION',
	GET_TENANT_IDENT_DOCUMENT_ACTION 						: 	'GET_TENANT_IDENT_DOCUMENT_ACTION',
	GET_TENANT_SUPPORT_DOCUMENT_ACTION 						: 	'GET_TENANT_SUPPORT_DOCUMENT_ACTION',

	UPDATE_TENANT_DETAILS_ACTION 							: 	'UPDATE_TENANT_DETAILS_ACTION',
	UPDATE_TENANT_RESIDENT_INFO_ACTION 						: 	'UPDATE_TENANT_RESIDENT_INFO_ACTION',
	UPDATE_TENANT_PETS_INFO_ACTION 							: 	'UPDATE_TENANT_PETS_INFO_ACTION',
	UPDATE_TENANT_CURRENT_RES_INFO_ACTION 					: 	'UPDATE_TENANT_CURRENT_RES_INFO_ACTION',
	UPDATE_TENANT_PRE_RES_INFO_ACTION 						: 	'UPDATE_TENANT_PRE_RES_INFO_ACTION',
	UPDATE_TENANT_CURRENT_EMP_ACTION 						: 	'UPDATE_TENANT_CURRENT_EMP_ACTION',
	UPDATE_TENANT_PREVIOUS_EMP_ACTION 						: 	'UPDATE_TENANT_PREVIOUS_EMP_ACTION',
	UPDATE_TENANT_PERSONAL_REF_ACTION 						: 	'UPDATE_TENANT_PERSONAL_REF_ACTION',
	UPLOAD_TENANT_IDENTITY_DOC_ACTION 						: 	'UPLOAD_TENANT_IDENTITY_DOC_ACTION',

	DELETE_CO_APPLICANT_INFO_ACTION 						: 	'DELETE_CO_APPLICANT_INFO_ACTION',
	DELETE_TENANT_PETS_INFO_ACTION							: 	'DELETE_TENANT_PETS_INFO_ACTION',
	DELETE_TENANT_IDENT_DOCUMENT_ACTION 					: 	'DELETE_TENANT_IDENT_DOCUMENT_ACTION',
	
	CLEAR_GET_TENANT_DETAILS_ACTION 						: 	'CLEAR_GET_TENANT_DETAILS_ACTION',
	CLEAR_UPDATE_TENANT_DETAILS_ACTION 						: 	'CLEAR_UPDATE_TENANT_DETAILS_ACTION',
	CLEAR_GET_TENANT_RESIDENT_INFO_ACTION 					: 	'CLEAR_GET_TENANT_RESIDENT_INFO_ACTION',
	CLEAR_UPDATE_TENANT_RESIDENT_INFO_ACTION 				: 	'CLEAR_UPDATE_TENANT_RESIDENT_INFO_ACTION',
	CLEAR_GET_TENANT_PETS_INFO_ACTION 						: 	'CLEAR_GET_TENANT_PETS_INFO_ACTION',
	CLEAR_UPDATE_TENANT_PETS_INFO_ACTION 					: 	'CLEAR_UPDATE_TENANT_PETS_INFO_ACTION',
	CLEAR_DELETE_TENANT_PETS_INFO_ACTION 					: 	'CLEAR_DELETE_TENANT_PETS_INFO_ACTION',
	CLEAR_GET_TENANT_CURRENT_RES_INFO_ACTION 				: 	'CLEAR_GET_TENANT_CURRENT_RES_INFO_ACTION',
	CLEAR_UPDATE_TENANT_CURRENT_RES_INFO_ACTION 			: 	'CLEAR_UPDATE_TENANT_CURRENT_RES_INFO_ACTION',
	CLEAR_GET_TENANT_PRE_RES_INFO_ACTION 					: 	'CLEAR_GET_TENANT_PRE_RES_INFO_ACTION',
	CLEAR_UPDATE_TENANT_PRE_RES_INFO_ACTION 				: 	'CLEAR_UPDATE_TENANT_PRE_RES_INFO_ACTION',
	CLEAR_GET_TENANT_CURRENT_EMP_ACTION 					: 	'CLEAR_GET_TENANT_CURRENT_EMP_ACTION',
	CLEAR_UPDATE_TENANT_CURRENT_EMP_ACTION 					: 	'CLEAR_UPDATE_TENANT_CURRENT_EMP_ACTION',
	CLEAR_GET_TENANT_PREVIOUS_EMP_ACTION 					: 	'CLEAR_GET_TENANT_PREVIOUS_EMP_ACTION',
	CLEAR_UUPDATE_TENANT_PREVIOUS_EMP_ACTION 				: 	'CLEAR_UUPDATE_TENANT_PREVIOUS_EMP_ACTION',
	CLEAR_GET_TENANT_PERSONAL_REF_ACTION 					: 	'CLEAR_GET_TENANT_PERSONAL_REF_ACTION',
	CLEAR_UPDATE_TENANT_PERSONAL_REF_ACTION 				: 	'CLEAR_UPDATE_TENANT_PERSONAL_REF_ACTION',
	CLEAR_UPLOAD_TENANT_IDENTITY_DOC_ACTION 				: 	'CLEAR_UPLOAD_TENANT_IDENTITY_DOC_ACTION',


	GET_WEATHER_UPDATES_ACTION 								: 	'GET_WEATHER_UPDATES_ACTION',
	CLEAR_WEATHER_UPDATES_ACTION 							: 	'CLEAR_WEATHER_UPDATES_ACTION',

	GET_TENANT_BID_DETAILS_ACTION 							: 	'GET_TENANT_BID_DETAILS_ACTION',
	CLEAR_TENANT_BID_DETAILS_ACTION 						: 	'CLEAR_TENANT_BID_DETAILS_ACTION',
	
}

export default ACTION_TYPES